### ISSUE TITLE
Use YAML for all service descriptors

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/pipelines#30]
API already supports it - just need to convert the JSON ones to YAML and test.

**Comment by tdudgeon** [comment]
Initial commit made converting all service descriptors in pipelines to YAML format.
These seem to work in Squonk, but the test framework does not handle files in YAML.

Also needed once the tests are sorted:
1. convert the other peipleines projects (e.g. sygnature) to YAML
2. test each one in Squonk as the key thing that changes in the convertsion is the `command` property that is executed (or presumably the tests should catch any mistakes with this?)

**Comment by tdudgeon** [comment]
Just for the record, all JSON format service descriptors were converted to YAML using this web site: https://www.json2yaml.com/

After conversion the `command` property was manually fixed to reflect the ability to use multi-line text.
No other fields were manually changed. There is a possibility that the `command` properties may not be correct.

**Comment by alanbchristie** [comment]
Changes merged to master
